### ISSUE TITLE
bors/homu should set S- tags

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust-central-station#16]
when bors acknowledges a commit, set to S-waiting-on-bors, if a merge fails, set to S-waiting-on-author. There would still be some manual work, but significantly less.

**Comment by tomprince** [comment]
For reference, servo handles this in highfive:
- https://github.com/servo/highfive/blob/master/handlers/homu_status/__init__.py#L67
- https://github.com/servo/highfive/blob/master/handlers/status_update/__init__.py#L72-L74
