### ISSUE TITLE
Letsencrypt is broken in a long-running RCS container, and can only be fixed by chance

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust-central-station#51]
https://mozilla.logbot.info/rust-infra/20180620#c14911644-c14911887

a) it seems to not renew unless the whole container is restarted
b) it only seems to renew on container restart because the certificates revert back to ones from 2017 somehow, despite the whole letsencrypt directory being mounted into the container. This seems obviously wrong, but on the plus side does provide a workaround for a

**Comment by emilyalbini** [comment]
We're not using RCS anymore, so closing this issue.
