### ISSUE TITLE
Directory listing generation should be faster

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust-central-station#58]
Today this takes ~15 minutes which is quite long and with the current approach will only grow.

There are two incremental steps here:
 - We should only be generating an index for the "current upload"; not for the whole bucket. This is probably relatively easy and would be enough for quite a while.
 - Stop generating indices at upload and generate them client-side via a custom 404 page.

**Comment by kennytm** [comment]
Context: 

* https://github.com/rust-lang/rust-central-station/blob/edbd48a4306b57b0029375cc62c28b0fcc130f1c/Dockerfile#L70-L78
* "it's for things like https://static.rust-lang.org/dist/2018-06-26/index.html"
* discussion: https://discordapp.com/channels/442252698964721669/443148319431065610/463408362139156520

**Comment by Mark-Simulacrum** [comment]
This should no longer run on deploys so I'm closing the issue
