### ISSUE TITLE
Add ability to roll back a nightly rust release

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust-central-station#8]
We should have the ability to "roll back" the latest nightly release in case of breakage such as rustup is incompatible with the manifest and/or artifacts or when the artifacts themselves are just busted. This rollback should be a documented command that's probably a subset of the `promote-release` binary. This command would just take the artifacts from the previous night and redeploy them to the non-archive locations.

**Comment by pietroalbini** [comment]
The [new `promote-release`](https://github.com/rust-lang/promote-release) supports releasing multiple nightlies in the same day, so it's possible to rollback by simply running the release again with the `PROMOTE_RELEASE_ALLOW_MULTIPLE_TODAY` environment variable. Running the command takes 30 minutes.
