### ISSUE TITLE
Gate rustc on both Azure and (GitHub Actions - macOS)

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust-central-station#848]
Gate rustc CI on both Azure and GitHub Actions with the exception of macOS
builders to quickly detect builds that will inevitably fail on Azure, while
avoiding spurious failures described in rust-lang/rust#71988.

Time to failure (TTF) on Azure and GitHub Actions (GHA) from a few different
rollups (measurements for GHA include non-spurious failures from macOS builders
under simplifying assumption that they would also fail elsewhere around the
same time):

| Rollup | Azure TTF  | GHA TTF |
|--------|------------|---------|
| 73271  | 1h 48m  1s | 22m  4s |
| 73240  | 1h  7m 30s | 23m 52s |
| 73231  | 2h 22m 45s | 25m 48s |
| 73168  | 1h 50m 34s | 23m 41s |
| 73064  | 2h 19m 42s | 42m 13s |
| 73062  | 1h 58m 42s | 41m 24s |
| 73053  | 2h  5m 57s | 37m 32s |

Potential drawbacks: increased likelihood of spurious failures.

**Comment by pietroalbini** [comment]
That's a great point! Added this to this week's infrastructure team meeting.

**Comment by tmiasko** [comment]
Blocked on recently introduced failures on arm-android & GitHub Actions rust-lang/rust#73535.
