### ISSUE TITLE
Add license to rust-central-station

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust-central-station#886]
rust-central-station doesn't currently have any Open Source licensing explicitly listed. We'd like to relicense rust-central-station to Rust's standard `MIT OR Apache-2.0` license, so that we can freely copy code between it and other Rust projects. In order to safely do that, we would like explicit permission from the following people:

* [x] @Mark-Simulacrum
* [x] @RalfJung
* [x] @SimonSapin
* [x] @aidanhs
* [x] @alexcrichton
* [x] @aturon
* [x] @davidtwco
* [x] @frewsxcv
* [x] @kennytm
* [x] @oli-obk
* [x] @phansch
* [x] @pietroalbini
* [x] @thibaultdelor

If you're OK with us using your contributions under Rust's standard Open Source license, please post a comment copy-pasting the following:

> I agree to license my contributions to rust-central-station under Rust's standard `MIT OR Apache-2.0` dual-license.

We'll track approvals using the checkboxes above, and once we have all the boxes checked, we'll relicense the repository.

Thank you!

**Comment by pietroalbini** [comment]
I agree to license my contributions to rust-central-station under Rust's standard `MIT OR Apache-2.0` dual-license.

**Comment by davidtwco** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by oli-obk** [comment]
I agree to license my contributions to rust-central-station under Rust's standard `MIT OR Apache-2.0` dual-license.

**Comment by phansch** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by thibaultdelor** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by RalfJung** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by SimonSapin** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by kennytm** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by frewsxcv** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by Mark-Simulacrum** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by alexcrichton** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by aidanhs** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by aturon** [comment]
I agree to license my contributions to rust-central-station under Rust's standard MIT OR Apache-2.0 dual-license.

**Comment by pietroalbini** [comment]
The repository is now licensed under "MIT OR Apache-2.0"! Thanks everyone :heart:
